### ISSUE TITLE
maxWidth or maxHeight

### ISSUE THREAD

**Issue by psuslick** [nanlabs/react-native-scaled-image#1]
A beneficial addition would be the inclusion of maxWidth or maxHeight. Currently if you have a ScrollView of image assets, you cannot assign a maxWidth correctly. This proves problematic if you want to set a series of images to a specific height and have them dynamical resize, but restrict the resize to a maximum value (i.e. logos with vastly different dimensions).

Is there a way to accomplish this?

**Comment by germanst** [comment]
You should pass `maxWidth` inside styles, it should work because internally we use `Image` component from react native and we're passing to it all received styles. According CSS documentation the value of the max-width property overrides the height property.
You could try something like this:
```
<ScaledImage source={localImage} height={100} styles={{maxWidth: 200}} />
```
Tell me if it works. Regards!
